version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        REACT_APP_BACKEND_APP_HOST: ${REACT_APP_BACKEND_APP_HOST}
        REACT_APP_BACKEND_APP_PORT: ${REACT_APP_BACKEND_APP_PORT}
        REACT_APP_BACKEND_APP_BASE_URL: ${REACT_APP_BACKEND_APP_BASE_URL}
    ports:
      - "3000:80"
    environment:
      - REACT_APP_BACKEND_APP_HOST=${REACT_APP_BACKEND_APP_HOST}
      - REACT_APP_BACKEND_APP_PORT=${REACT_APP_BACKEND_APP_PORT}
      - REACT_APP_BACKEND_APP_BASE_URL=${REACT_APP_BACKEND_APP_BASE_URL}
    env_file:
      - .env # Explicitly load the .env file
    volumes:
      - .:/app
      - /app/node_modules
